version: '3.8'

services:
  db:
    container_name: mysql-server-in-docker
    image: mysql-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: backend/db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: "!aA12345"
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: DespesasPessoaisDB
      LANG: C.UTF-8
    ports:
      - "3308:3306"
    networks:
      - despesas-network

  backend:
    container_name: api-back-end
    image: back-end    
    restart: always
    build:
      context: .
      dockerfile: backend/Dockerfile    
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "5001:5000"      
    depends_on:
      - db
    networks:
      - despesas-network

  frontend:
    container_name: web-front-end
    image: front-end
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - despesas-network

networks:
    despesas-network:
        driver: bridge